model_params:
  mask_layer_type: ConvMask
  model_name: resnet50 
dataset:
  dataset_name: ImageNet
  batch_size: 128 ## assumes 4 gpus
  num_workers: 16
  data_root_dir: ./experiments
prune_params:
  prune_rate: 0.2
  prune_method: mag 
  target_sparsity: 0.999
experiment_params:
  seed: 0
  base_dir: ./experiments 
  training_type: lrr
  training_precision: bfloat16
  epochs_per_level: 90
optimizer:
  lr: 0.2
  momentum: 0.9
  weight_decay: 1e-4
  scheduler_type: TriangularSchedule
  lr_start: 0.2
  lr_peak: 1
  lr_end: 0.0
cyclic_training:
  num_cycles: 1
  strategy: constant
wandb_params:
  project_name: placeholder
dist_params:
  distributed: 'true'
