model_params:
  mask_layer_type: ConvMask
  model_name: resnet18 
dataset:
  dataset_name: CIFAR10
  batch_size: 512 
  num_workers: 32
  data_root_dir: ./experiments
prune_params:
  prune_method: random_balanced 
  prune_rate: 0.2
  target_sparsity: 0.999
experiment_params:
  base_dir: ./experiments 
  seed: 0
  training_type: lrr 
  training_precision: bfloat16
  use_compile: '' 
optimizer:
  lr: 0.2
  scheduler_type: TriangularSchedule
  weight_decay: 5e-4
  momentum: 0.9
  peak_lr: 1
cyclic_training:
  num_cycles: 1
  epochs_per_level: 150
  strategy: constant
wandb_params:
  project_name: LRR_experiments
dist_params:
  distributed: False