model_params:
  mask_layer_type: ConvMask
  model_name: resnet50 
dataset:
  dataset_name: CIFAR100
  batch_size: 512 
  num_workers: 16
  data_root_dir: ./experiments
prune_params:
  prune_method: mag
  prune_rate: 0.2
  target_sparsity: 0.999
experiment_params:
  base_dir: ./experiments 
  seed: 0
  training_type: lrr
  training_precision: bfloat16
  use_compile: 'false'
  compute_metrics: 'true'
optimizer:
  scheduler_type: TriangularSchedule
  weight_decay: 1e-3
  momentum: 0.9
  lr_start: 0.2
  lr_peak: 1
  lr_end: 0.01
  skip_warmup: 'false'
cyclic_training:
  num_cycles: 1 
  epochs_per_level: 150
  strategy: constant
  total_training_budget: 0
wandb_params:
  project_name: placeholder
dist_params:
  distributed: 'false'