model_params:
  conv_type: ConvMask
  bn_type: LearnedBatchNorm
  init: kaiming_normal
  nonlinearity: relu
  first_layer_type: None
  mode: fan_in
  scale_fan: False
  model_name: ResNet50
dataset:
  dataset_name: ImageNet
  num_classes: 1000
  batch_size: 256 
  num_workers: 8
prune_params:
  prune_rate: 0.2
  er_init: 0.105
  er_method: just dont 
  prune_method: synflow
experiment_params:
  epochs_per_level: 90 
  num_levels: 30
  training_type: wr
optimizer:
  lr: 0.1
  scheduler_type: CosineLRWarmup
  warmup_epochs: 10
  lr_min: 0.01
