model_params:
  mask_layer_type: ConvMask
  model_name: resnet50 
dataset:
  dataset_name:  
  batch_size: 512 
  num_workers: 16
  data_root_dir: ./experiments
prune_params:
  prune_method: snip
  prune_rate: 0.2
  target_sparsity: 0.95
experiment_params:
  base_dir: ./experiments 
  seed: 0
  training_type: lrr
  training_precision: bfloat16
  use_compile: false 
  compute_metrics: true 
optimizer:
  lr: 0.2
  scheduler_type: TriangularSchedule
  weight_decay: 1e-3
  momentum: 0.9
  peak_lr: 1
  skip_warmup: false
cyclic_training:
  num_cycles: 1 
  epochs_per_level: 150
  strategy: constant
wandb_params:
  project_name: LRR_experiments
dist_params:
  distributed: false
