model_params:
  conv_type: ConvMask
  model_name: resnet18 
dataset:
  dataset_name: CIFAR10 
  num_classes: 10
  batch_size: 256
  num_workers: 16
  data_root: /home/c02hane/CISPA-projects/ffcv_imagenet-2023
prune_params:
  prune_rate: 0.2
  prune_method: mag
  num_levels: 25 
experiment_params:
  epochs_per_level: 150 
  training_type: lrr
  base_dir: /home/c02hane/CISPA-projects/neuron_pruning-2024/TurboPrune/experiments
optimizer:
  lr: 0.1
  scheduler_type: MultiStepLRWarmup
  warmup_epochs: 10
  weight_decay: 5e-4
dist_params:
  port: 12350