model_params:
  conv_type: ConvMask
  model_name: resnet18
dataset:
  dataset_name: ImageNet
  num_classes: 1000
  batch_size: 256
  num_workers: 16
  data_root: ./ 
prune_params:
  prune_rate: 0.2
  prune_method: mag 
  num_levels: 25
experiment_params:
  epochs_per_level: 90
  training_type: lrr 
  expt_setup: other 
optimizer:
  lr: 0.1
  scheduler_type: ImageNetLRDropsWarmup
  warmup_epochs: 10
  lr_min: 0.01
dist_params:
  port: 12355