dataset_name: ImageNet
data_root_dir: ./data

seed: 0
base_dir: ./experiments

batch_size: 128
num_workers: 16
epochs_per_level: 90
imagenet_dataloader_type: ffcv

training_precision: bfloat16
distributed: true
resume_experiment: false
resume_experiment_stuff: null
wandb_project_name: 'TurboPrune_runs'

